# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: driver.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x64river.proto\"!\n\x11\x41ssignTaskRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"!\n\x0e\x41signTaskReply\x12\x0f\n\x07message\x18\x01 \x01(\t2>\n\x06\x44river\x12\x34\n\x0b\x61ssign_task\x12\x12.AssignTaskRequest\x1a\x0f.AsignTaskReply\"\x00\x62\x06proto3')



_ASSIGNTASKREQUEST = DESCRIPTOR.message_types_by_name['AssignTaskRequest']
_ASIGNTASKREPLY = DESCRIPTOR.message_types_by_name['AsignTaskReply']
AssignTaskRequest = _reflection.GeneratedProtocolMessageType('AssignTaskRequest', (_message.Message,), {
  'DESCRIPTOR' : _ASSIGNTASKREQUEST,
  '__module__' : 'driver_pb2'
  # @@protoc_insertion_point(class_scope:AssignTaskRequest)
  })
_sym_db.RegisterMessage(AssignTaskRequest)

AsignTaskReply = _reflection.GeneratedProtocolMessageType('AsignTaskReply', (_message.Message,), {
  'DESCRIPTOR' : _ASIGNTASKREPLY,
  '__module__' : 'driver_pb2'
  # @@protoc_insertion_point(class_scope:AsignTaskReply)
  })
_sym_db.RegisterMessage(AsignTaskReply)

_DRIVER = DESCRIPTOR.services_by_name['Driver']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ASSIGNTASKREQUEST._serialized_start=16
  _ASSIGNTASKREQUEST._serialized_end=49
  _ASIGNTASKREPLY._serialized_start=51
  _ASIGNTASKREPLY._serialized_end=84
  _DRIVER._serialized_start=86
  _DRIVER._serialized_end=148
# @@protoc_insertion_point(module_scope)
