# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: driver.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x64river.proto\x1a\x0c\x63ommon.proto\"\x0c\n\nworkerPort\",\n\x0c\x61ssignedTask\x12\x10\n\x08taskType\x18\x01 \x01(\x05\x12\n\n\x02id\x18\x02 \x01(\x05\x32\x81\x01\n\x06\x44river\x12&\n\x12registerWorkerPort\x12\x06.empty\x1a\x06.empty\"\x00\x12)\n\x15requestTaskAssignment\x12\x06.empty\x1a\x06.empty\"\x00\x12$\n\x10notifyTaskStatus\x12\x06.empty\x1a\x06.empty\"\x00\x62\x06proto3')



_WORKERPORT = DESCRIPTOR.message_types_by_name['workerPort']
_ASSIGNEDTASK = DESCRIPTOR.message_types_by_name['assignedTask']
workerPort = _reflection.GeneratedProtocolMessageType('workerPort', (_message.Message,), {
  'DESCRIPTOR' : _WORKERPORT,
  '__module__' : 'driver_pb2'
  # @@protoc_insertion_point(class_scope:workerPort)
  })
_sym_db.RegisterMessage(workerPort)

assignedTask = _reflection.GeneratedProtocolMessageType('assignedTask', (_message.Message,), {
  'DESCRIPTOR' : _ASSIGNEDTASK,
  '__module__' : 'driver_pb2'
  # @@protoc_insertion_point(class_scope:assignedTask)
  })
_sym_db.RegisterMessage(assignedTask)

_DRIVER = DESCRIPTOR.services_by_name['Driver']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _WORKERPORT._serialized_start=30
  _WORKERPORT._serialized_end=42
  _ASSIGNEDTASK._serialized_start=44
  _ASSIGNEDTASK._serialized_end=88
  _DRIVER._serialized_start=91
  _DRIVER._serialized_end=220
# @@protoc_insertion_point(module_scope)
